  allocate (MASK_CELL(NX,NY),  MASK_NODE(0:NX,0:NY))
  allocate( MASK1X(NX,0:NY), MASK1Y(0:NX,NY))
allocate (  MASK2X(NX,NY),MASK2Y(NX,NY))
    allocate(u0x(0:NX,0:NY), u0y(0:NX,0:NY))
     allocate(u1x(0:NX,0:NY), u1y(0:NX,0:NY))
      allocate(u2x(0:NX,0:NY), u2y(0:NX,0:NY))
allocate(       corr_ux(0:NX,0:NY), corr_uy(0:NX,0:NY))

  
    allocate(C(3,3,NX,NY), rho(NX,NY))
allocate(    INV_MASS(0:NX,0:NY))

    allocate(X_rec(num_rec), Y_rec(num_rec))

    allocate (NX_rec(num_rec), NY_rec(num_rec))
   allocate(    inpo_rec(3,3,num_rec))

  
  allocate(  outfname_rec(num_rec))
!----------------valuables for CPML-------------------------------------
   allocate ( a1_lef(NX_CPML_lef), a1_rig(NX - NX_CPML_rig+1:NX), a1_btm(NY_CPML_btm))
    allocate (  b1_lef(NX_CPML_lef), b1_rig(NX - NX_CPML_rig+1:NX), b1_btm(NY_CPML_btm))
   allocate (   a2_lef(0:NX_CPML_lef), a2_rig(NX - NX_CPML_rig:NX), a2_btm(0:NY_CPML_btm))
    allocate ( b2_lef(0:NX_CPML_lef), b2_rig(NX - NX_CPML_rig:NX), b2_btm(0:NY_CPML_btm))

  allocate (dux_dx_lef(NX_CPML_lef,0:NY))
allocate (duy_dx_lef(NX_CPML_lef,0:NY))
allocate (dux_dx_rig(NX - NX_CPML_rig+1:NX,0:NY))
allocate (duy_dx_rig(NX - NX_CPML_rig+1:NX,0:NY))
allocate (dux_dy_btm(0:NX,NY_CPML_btm))
allocate (duy_dy_btm(0:NX,NY_CPML_btm))
allocate (dTxx_dx_lef(0:NX_CPML_lef,0:NY))
allocate (dTyx_dx_lef(0:NX_CPML_lef,0:NY))
allocate (dTxx_dx_rig(NX - NX_CPML_rig:NX,0:NY))
allocate (dTyx_dx_rig(NX - NX_CPML_rig:NX,0:NY))
allocate (dTxy_dy_btm(0:NX,0:NY_CPML_btm))
allocate (dTyy_dy_btm(0:NX,0:NY_CPML_btm))

allocate (mem1_xx_lef(NX_CPML_lef,0:NY))
allocate (mem1_xy_lef(NX_CPML_lef,0:NY))
allocate (mem1_xx_rig(NX - NX_CPML_rig+1:NX,0:NY))
allocate (mem1_xy_rig(NX - NX_CPML_rig+1:NX,0:NY))
allocate (mem1_yx_btm(0:NX,NY_CPML_btm))
allocate (mem1_yy_btm(0:NX,NY_CPML_btm))
allocate (mem2_xx_lef(0:NX_CPML_lef,0:NY))
allocate (mem2_xy_lef(0:NX_CPML_lef,0:NY))
allocate (mem2_xx_rig(NX - NX_CPML_rig:NX,0:NY))
allocate (mem2_xy_rig(NX - NX_CPML_rig:NX,0:NY))
allocate (mem2_yx_btm(0:NX,0:NY_CPML_btm))
allocate (mem2_yy_btm(0:NX,0:NY_CPML_btm))

allocate (corr_dux_dx_lef(NX_CPML_lef,0:NY))
allocate (corr_duy_dx_lef(NX_CPML_lef,0:NY))
allocate (corr_dux_dx_rig(NX - NX_CPML_rig+1:NX,0:NY))
allocate (corr_duy_dx_rig(NX - NX_CPML_rig+1:NX,0:NY))
allocate (corr_dux_dy_btm(0:NX,NY_CPML_btm))
allocate (corr_duy_dy_btm(0:NX,NY_CPML_btm))
allocate (corr_dTxx_dx_lef(0:NX_CPML_lef,0:NY))
allocate (corr_dTyx_dx_lef(0:NX_CPML_lef,0:NY))
allocate (corr_dTxx_dx_rig(NX - NX_CPML_rig:NX,0:NY))
allocate (corr_dTyx_dx_rig(NX - NX_CPML_rig:NX,0:NY))
allocate (corr_dTxy_dy_btm(0:NX,0:NY_CPML_btm))
allocate (corr_dTyy_dy_btm(0:NX,0:NY_CPML_btm))

allocate (corr_mem1_xx_lef(NX_CPML_lef,0:NY))
allocate (corr_mem1_xy_lef(NX_CPML_lef,0:NY))
allocate (corr_mem1_xx_rig(NX - NX_CPML_rig+1:NX,0:NY))
allocate (corr_mem1_xy_rig(NX - NX_CPML_rig+1:NX,0:NY))
allocate (corr_mem1_yx_btm(0:NX,NY_CPML_btm))
allocate (corr_mem1_yy_btm(0:NX,NY_CPML_btm))
allocate (corr_mem2_xx_lef(0:NX_CPML_lef,0:NY))
allocate (corr_mem2_xy_lef(0:NX_CPML_lef,0:NY))
allocate (corr_mem2_xx_rig(NX - NX_CPML_rig:NX,0:NY))
allocate (corr_mem2_xy_rig(NX - NX_CPML_rig:NX,0:NY))
allocate (corr_mem2_yx_btm(0:NX,0:NY_CPML_btm))
allocate (corr_mem2_yy_btm(0:NX,0:NY_CPML_btm))
!-----------END CPML--------------------------------------------------------
